version: '3.8'

services:
  nginx:
    # container_name: "nginx-container"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    env_file: ./.env
    ports:
      - $NGINX_LOCAL_PORT:$NGINX_DOCKER_PORT
    volumes:
      - "./client/build:/usr/share/nginx/html"
    networks:
      - pvs-network
    depends_on:
      - react

  react: 
    # container_name: "react-container"
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    env_file: ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - "./react:/usr/src"
    tty: true
    working_dir: /usr/src
    networks:
      - pvs-network
    depends_on:
      - express

  express:
    # container_name: 'express-container'
    build:
      context: .
      dockerfile: ./docker/express/Dockerfile
    env_file: ./.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=express/app:*
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - NODE_ENV=development
    tty: true
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - "./express/:/usr/src/app"
    working_dir: /usr/src/app
    networks:
      - pvs-network
    depends_on:
      - mongodb

  gumtree:
    # container_name: 'gumtree-container'
    build:
      context: .
      dockerfile: ./docker/gumtree/Dockerfile
    tty: true
    stdin_open: true
    env_file: ./.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=express/app:*
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - NODE_ENV=development
    ports: 
      - "4567:4567"
    volumes: 
      - "./gumtree/:/usr/src/app"
      - "./c_lang/:/diff"
    working_dir: /usr/src/app
    networks:
      - pvs-network
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:5.0.2
    # container_name: 'mongodb-container'
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      # - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongo/db:/data/db
    networks:
      - pvs-network
  
  mongo-express:
    image: mongo-express
    # container_name: 'mongo-express-container'
    restart: always
    env_file: ./.env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGO_EXPRESS_LOCAL_PORT:$MONGO_EXPRESS_DOCKER_PORT
    networks:
      - pvs-network

networks:
  pvs-network:
    driver: bridge

volumes:
  db:
    driver: local


